%General Mission Analysis Tool(GMAT) Script
%Created: 2026-06-08 18:01:16


%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft DefaultSC;
DefaultSC.DateFormat = UTCGregorian;
DefaultSC.Epoch = '01 Jul 2027 08:52:00.000';
DefaultSC.CoordinateSystem = EarthMJ2000Eq;
DefaultSC.DisplayStateType = Keplerian;
DefaultSC.SMA = 6970.999999999998;
DefaultSC.ECC = 8.626879834525431e-18;
DefaultSC.INC = 97.7877;
DefaultSC.RAAN = 77.1537;
DefaultSC.AOP = 0;
DefaultSC.TA = 0;
DefaultSC.DryMass = 850;
DefaultSC.Cd = 2.2;
DefaultSC.Cr = 1.8;
DefaultSC.DragArea = 15;
DefaultSC.SRPArea = 1;
DefaultSC.SPADDragScaleFactor = 1;
DefaultSC.SPADSRPScaleFactor = 1;
DefaultSC.AtmosDensityScaleFactor = 1;
DefaultSC.ExtendedMassPropertiesModel = 'None';
DefaultSC.NAIFId = -10000001;
DefaultSC.NAIFIdReferenceFrame = -9000001;
DefaultSC.OrbitColor = Red;
DefaultSC.TargetColor = Teal;
DefaultSC.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
DefaultSC.CdSigma = 1e+70;
DefaultSC.CrSigma = 1e+70;
DefaultSC.Id = 'SatId';
DefaultSC.Attitude = CoordinateSystemFixed;
DefaultSC.SPADSRPInterpolationMethod = Bilinear;
DefaultSC.SPADSRPScaleFactorSigma = 1e+70;
DefaultSC.SPADDragInterpolationMethod = Bilinear;
DefaultSC.SPADDragScaleFactorSigma = 1e+70;
DefaultSC.AtmosDensityScaleFactorSigma = 1e+70;
DefaultSC.ModelFile = 'aura.3ds';
DefaultSC.ModelOffsetX = 0;
DefaultSC.ModelOffsetY = 0;
DefaultSC.ModelOffsetZ = 0;
DefaultSC.ModelRotationX = 0;
DefaultSC.ModelRotationY = 0;
DefaultSC.ModelRotationZ = 0;
DefaultSC.ModelScale = 1;
DefaultSC.AttitudeDisplayStateType = 'Quaternion';
DefaultSC.AttitudeRateDisplayStateType = 'AngularVelocity';
DefaultSC.AttitudeCoordinateSystem = EarthMJ2000Eq;
DefaultSC.EulerAngleSequence = '321';

%----------------------------------------
%---------- GroundStations
%----------------------------------------

Create GroundStation MadridGS;
MadridGS.OrbitColor = Thistle;
MadridGS.TargetColor = DarkGray;
MadridGS.CentralBody = Earth;
MadridGS.StateType = Spherical;
MadridGS.HorizonReference = Sphere;
MadridGS.Location1 = 40.4;
MadridGS.Location2 = 352.2962;
MadridGS.Location3 = 0.2;
MadridGS.Id = 'MadridGS';
MadridGS.IonosphereModel = 'None';
MadridGS.TroposphereModel = 'None';
MadridGS.DataSource = 'Constant';
MadridGS.Temperature = 295.1;
MadridGS.Pressure = 1013.5;
MadridGS.Humidity = 55;
MadridGS.MinimumElevationAngle = 10;






%----------------------------------------
%---------- ForceModels
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;
DefaultProp_ForceModel.CentralBody = Earth;
DefaultProp_ForceModel.PrimaryBodies = {Earth};
DefaultProp_ForceModel.Drag = None;
DefaultProp_ForceModel.SRP = Off;
DefaultProp_ForceModel.RelativisticCorrection = Off;
DefaultProp_ForceModel.ErrorControl = RSSStep;
DefaultProp_ForceModel.GravityField.Earth.Degree = 4;
DefaultProp_ForceModel.GravityField.Earth.Order = 4;
DefaultProp_ForceModel.GravityField.Earth.StmLimit = 100;
DefaultProp_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof';
DefaultProp_ForceModel.GravityField.Earth.TideModel = 'None';

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator DefaultProp;
DefaultProp.FM = DefaultProp_ForceModel;
DefaultProp.Type = RungeKutta89;
DefaultProp.InitialStepSize = 60;
DefaultProp.Accuracy = 9.999999999999999e-12;
DefaultProp.MinStep = 0.001;
DefaultProp.MaxStep = 2700;
DefaultProp.MaxStepAttempts = 50;
DefaultProp.StopIfAccuracyIsViolated = true;

%----------------------------------------
%---------- EventLocators
%----------------------------------------

Create EclipseLocator EclipseLocator1;
EclipseLocator1.Spacecraft = DefaultSC;
EclipseLocator1.Filename = 'C:\Users\mauga\Claude\Projects\GMAT-Masks Code\10_30_SSO\EclipseLocator1.txt';
EclipseLocator1.OccultingBodies = {Earth, Luna};
EclipseLocator1.InputEpochFormat = 'TAIModJulian';
EclipseLocator1.InitialEpoch = '21545';
EclipseLocator1.StepSize = 1;
EclipseLocator1.FinalEpoch = '21545.138';
EclipseLocator1.UseLightTimeDelay = true;
EclipseLocator1.UseStellarAberration = true;
EclipseLocator1.WriteReport = true;
EclipseLocator1.RunMode = Automatic;
EclipseLocator1.UseEntireInterval = true;
EclipseLocator1.EclipseTypes = {'Umbra', 'Penumbra', 'Antumbra'};

%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create OrbitView DefaultOrbitView;
DefaultOrbitView.SolverIterations = Current;
DefaultOrbitView.UpperLeft = [ 0.001431639226914817 0 ];
DefaultOrbitView.Size = [ 0.5003579098067287 0.4507462686567164 ];
DefaultOrbitView.RelativeZOrder = 13;
DefaultOrbitView.Maximized = false;
DefaultOrbitView.Add = {DefaultSC, Earth};
DefaultOrbitView.CoordinateSystem = EarthMJ2000Eq;
DefaultOrbitView.DrawObject = [ true true ];
DefaultOrbitView.DataCollectFrequency = 1;
DefaultOrbitView.UpdatePlotFrequency = 50;
DefaultOrbitView.NumPointsToRedraw = 0;
DefaultOrbitView.ShowPlot = true;
DefaultOrbitView.MaxPlotPoints = 20000;
DefaultOrbitView.ShowLabels = true;
DefaultOrbitView.ViewPointReference = Earth;
DefaultOrbitView.ViewPointVector = [ 30000 0 0 ];
DefaultOrbitView.ViewDirection = Earth;
DefaultOrbitView.ViewScaleFactor = 1;
DefaultOrbitView.ViewUpCoordinateSystem = EarthMJ2000Eq;
DefaultOrbitView.ViewUpAxis = Z;
DefaultOrbitView.EclipticPlane = Off;
DefaultOrbitView.XYPlane = On;
DefaultOrbitView.WireFrame = Off;
DefaultOrbitView.Axes = On;
DefaultOrbitView.Grid = Off;
DefaultOrbitView.SunLine = Off;
DefaultOrbitView.UseInitialView = On;
DefaultOrbitView.StarCount = 7000;
DefaultOrbitView.EnableStars = On;
DefaultOrbitView.EnableConstellations = On;

Create GroundTrackPlot DefaultGroundTrackPlot;
DefaultGroundTrackPlot.SolverIterations = Current;
DefaultGroundTrackPlot.UpperLeft = [ 0.001431639226914817 0.4507462686567164 ];
DefaultGroundTrackPlot.Size = [ 0.5003579098067287 0.4507462686567164 ];
DefaultGroundTrackPlot.RelativeZOrder = 19;
DefaultGroundTrackPlot.Maximized = false;
DefaultGroundTrackPlot.Add = {DefaultSC, MadridGS};
DefaultGroundTrackPlot.DataCollectFrequency = 1;
DefaultGroundTrackPlot.UpdatePlotFrequency = 50;
DefaultGroundTrackPlot.NumPointsToRedraw = 0;
DefaultGroundTrackPlot.ShowPlot = true;
DefaultGroundTrackPlot.MaxPlotPoints = 20000;
DefaultGroundTrackPlot.CentralBody = Earth;
DefaultGroundTrackPlot.TextureMap = 'ModifiedBlueMarble.jpg';


%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;
Propagate DefaultProp(DefaultSC) {DefaultSC.ElapsedDays = 1};
